"
" vimrc
"

let mapleader = ","
let g:auto_save = 1
let g:table_mode_corner='|'
let g:lightline = { 'colorscheme': 'wombat' }
let ayucolor="dark"

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
		\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

set runtimepath+=~/.vim

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
	\| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin("~/.vim/plugged")
" https://github.com/itchyny/lightline.vim
Plug 'itchyny/lightline.vim'
" https://github.com/gcmt/wildfire.vim
Plug 'gcmt/wildfire.vim'
" https://github.com/tpope/vim-surround
Plug 'tpope/vim-surround'
" https://github.com/airblade/vim-gitgutter
Plug 'airblade/vim-gitgutter'
" https://github.com/dhruvasagar/vim-table-mode
Plug 'dhruvasagar/vim-table-mode'
" https://github.com/907th/vim-auto-save
Plug '907th/vim-auto-save'
" https://github.com/iamcco/markdown-preview.nvim
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
" https://github.com/junegunn/fzf.vim
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" https://github.com/ayu-theme/ayu-vim
Plug 'ayu-theme/ayu-vim'
call plug#end()

syntax on
set cursorline
set termguicolors " enable true colors support.
colorscheme ayu

set number
set relativenumber

set scrolloff=10

set tabstop=2
set shiftwidth=2

set incsearch
set ignorecase
set smartcase
set hlsearch
exec "nohlsearch"

set wildmenu
set updatetime=0 " default is 4000ms.

set mouse=a

set laststatus=2
set noshowmode
set ttimeoutlen=0 " when press esc, back to normal-mode right away.

nnoremap s <nop>
nnoremap S :w<CR>
nnoremap Q :q<CR>
nnoremap R :source $MYVIMRC<CR>
nnoremap E :edit $MYVIMRC<CR>

nnoremap r :call Compiler()<CR>
func! Compiler()
	exec "w"
	if &filetype == "markdown"
		exec "MarkdownPreview"
	endif
endfunc

" search current dir using ripgrep.
nnoremap <C-f> :Rg<Space>

source ~/.config/vim/snippits.vim

