"
" vimrc
"

let mapleader = " "

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

set runtimepath+=~/.vim

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin("~/.vim/plugged")
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
Plug 'gcmt/wildfire.vim'
Plug 'tpope/vim-surround'
Plug 'connorholyday/vim-snazzy'
call plug#end()

syntax on

set cursorline
color snazzy
" highlight CursorLine cterm=NONE ctermbg=235
" highlight CursorLineNr cterm=NONE ctermbg=235

set scrolloff=10

set number
set relativenumber

set tabstop=2
set shiftwidth=2

set incsearch
set smartcase

set laststatus=2
set statusline=%F\ %m

set wildmenu

set ignorecase
set smartcase
set hlsearch
exec "nohlsearch"

nnoremap s <nop>
nnoremap S :w<CR>
nnoremap R :source $MYVIMRC<CR>
nnoremap <LEADER>ev :e $MYVIMRC<CR>
nnoremap <LEADER>sv :source $MYVIMRC<CR>

