
# Global properties
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=20

# Disk usage
[disk]
label=
interval=30

# Battery indicator
[battery]
label=
interval=1

# Date Time
[time]
command=date '+%Y-%m-%d %H:%M:%S'
label=
interval=1

