#!/usr/bin/env sh

alias ..="cd .."
alias ...="cd ../.."

alias q=exit
alias c=clear

alias mv="mv -i"
alias rm="rm -i"

alias j="fasd_cd -d"

alias vim=nvim
alias f=fish
alias tm=tmux
alias ra=ranger
alias open=xdg-open
alias s="neofetch | lolcat"
alias rl="source ~/.bashrc; echo bashrc reloaded."
alias fy="trans :zh" # https://github.com/soimort/translate-shell
alias ghs="sudo cat ${HOME}/code/access_token.github | xclip -sel clip"

# replacement of some cli-tools
alias cat=bat
alias du=dust   # disk-usage: https://github.com/bootandy/dust
alias df=duf
alias grep=rg   # ripgrep: https://github.com/BurntSushi/ripgrep
alias ps=procs

alias ls=exa
alias sl=exa
alias ll="ls -l"

