#!/usr/bin/env sh

alias ghs="sudo cat ${HOME}/Code/access_token.github | xclip -sel clip"

alias ..="cd .."
alias ...="cd ../.."

alias ls=exa
alias sl=exa

alias q=exit
alias c=clear
alias l="ls -l"
alias ll="ls -al"

alias mv="mv -i"
alias rm="rm -i"

alias s=screenfetch
alias open=xdg-open
alias ra=ranger
alias v=vim
alias f=fish
alias cat=bat
alias tm=tmux

alias rl="source ~/.bashrc; echo bashrc reloaded."

