# _____ __  __ _   ___  __    ____ ___  _   _ _____
#|_   _|  \/  | | | \ \/ /   / ___/ _ \| \ | |  ___|
#  | | | |\/| | | | |\  /   | |  | | | |  \| | |_
#  | | | |  | | |_| |/  \   | |__| |_| | |\  |  _|
#  |_| |_|  |_|\___//_/\_\___\____\___/|_| \_|_|
#                       |_____|
#
# 参考：
#   1. https://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/
#   2. https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
#   3. https://zhuanlan.zhihu.com/p/432256727
#   4. https://github.com/anishathalye/dotfiles/blob/master/tmux.conf

# ===
# === Basics
# ===

# start window numbers at 1 to match keyboard order with tmux order
set -g base-index 1

# start pane numbers at 1 to match keyboard order with tmux order
setw -g pane-base-index 1

# don't rename windows automatically
set-option -g allow-rename off

# reload the .tmux.conf file
bind r source-file ~/.tmux.conf \; display-message "configuration reloaded"

# ===
# === Status bar
# ===

set -g status-left ''
set -g status-style bg=colour235,fg=colour136
setw -g window-status-style fg=colour244
setw -g window-status-current-style fg=colour166

# ===
# === Pane
# ===

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
# unbind '"'
# unbind %

# https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

