
# ===
# === basic settings
# ===

set scroll_offset                       4
set column_ratios                       1,3,4
set line_numbers                        relative
set automatically_count_files           true
set display_size_in_main_column         true
set tilde_in_titlebar                   true
set hostname_in_titlebar                true
set show_selection_in_titlebar          true
set display_free_space_in_status_bar    true
set save_console_history                true
set nested_ranger_warning               true

# ===
# === basic maps
# ===

map ?  help
map q  quit
map :  console
map ;  console
map S  shell $SHELL
map !  console shell%space
map cd console cd%space

# ===
# === jumping around
# ===

map g? cd /usr/share/doc/ranger
map gR eval fm.cd(ranger.RANGERDIR)
map g/ cd /
map gr cd /
map gh cd ~
map gd cd ~/Desktop
map gc cd ~/Code
map gp cd ~/Pictures
map gv cd ~/Videos
map gl cd ~/Downloads
map gm cd /var/run/media/lpj
map gb cd ~/Bak

# ===
# === search settings
# ===

alias search scout -rs

map / console search%space
map n search_next
map N search_next forward=False

map <C-f> fzf_select

# ===
# === copy settings
# ===

map yn yank name
map y. yank name_without_extension
map yp yank path
map yd yank dir

# ===
# === fileSystem operations
# ===

map t console touch%space
map V console shell vim%space
map D console mkdir%space

map dD                  console delete
map <DELETE>            console delete
set confirm_on_delete   always

map dd cut
map ud uncut

map yy copy
map uy uncut

map pp paste

map a  rename_append
map A  eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"))
map i  eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"), position=7)
map cw eval fm.execute_console("bulkrename") if fm.thisdir.marked_items else fm.open_console("rename ")

# ===
# === Define keys for the console
# ===
# === Note: Unmapped keys are passed directly to the console.
# ===

cmap <allow_quantifiers> false

cmap <CR>           eval fm.ui.console.execute()

cmap <delete>       eval fm.ui.console.delete(0)
cmap <backspace>    eval fm.ui.console.delete(-1)

cmap <tab>          eval fm.ui.console.tab()
cmap <s-tab>        eval fm.ui.console.tab(-1)

cmap     <ESC>      eval fm.ui.console.close()
copycmap <ESC>      <C-c>

# cmap <C-k>        eval fm.ui.console.delete_rest(1)
# cmap <C-u>        eval fm.ui.console.delete_rest(-1)
# cmap <C-w>        eval fm.ui.console.delete_word()
# cmap <A-d>        eval fm.ui.console.delete_word(backward=False)
# cmap <A-t>        eval fm.ui.console.transpose_words()
# cmap <C-y>        eval fm.ui.console.paste()
# cmap <C-t>        eval fm.ui.console.transpose_chars()

# ===
# === mark files settings
# ===

map <Space> mark_files toggle=True
map v       mark_files all=True toggle=True

# ===
# === hidden file settings
# ===

set show_hidden     false
set hidden_filter   ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$
map <C-h>           set show_hidden!
map zh              set show_hidden!

# ===
# === preview settings
# === gnome-terminal is not supported by ueberzug
# ===

set preview_files       true
set preview_directories true
set collapse_preview    true
set preview_images true

set use_preview_script  true
set preview_script      ~/.config/ranger/scope.sh

set preview_images_method ueberzug

# ===
# === for touch-typing and vimer
# ===

map <UP>       move up=1
map <DOWN>     move down=1
map <LEFT>     move left=1
map <RIGHT>    move right=1
map <CR>       move right=1
map <HOME>     move to=0
map <END>      move to=-1
map <PAGEUP>   move up=1     pages=True
map <PAGEDOWN> move down=1   pages=True

copymap <UP>       k
copymap <DOWN>     j
copymap <LEFT>     h
copymap <RIGHT>    l
copymap <HOME>     gg
copymap <END>      G
copymap <PAGEUP>   <C-B>
copymap <PAGEDOWN> <C-D>

# ===
# === taskview settings
# ===

tmap     <ESC> taskview_close
copytmap <ESC> q Q w <C-c>
tmap     <C-l> redraw_window

